### PR TITLE
fix: file with spaces

### LINKED ISSUE #7: Support Spaces in file names
When you have files/pages that contain spaces (e.g `configure bot.md`) does the action treat those as separate pages and errors with the following message(s):
```
cp: can't stat 'wiki/configure.md': No such file or directory
```

The action should support spaces by f.e. replacing them with dashes (-).

### PR DESCRIPTION
**Pull request by mmornati**
# Broken Script

## Why?
When file names contain spaces the copy script is broken and impossible even to ask for `space` replace with the `_` char.

## What?
Improved the loop syntax, around the find result, to take care of the correct filename, with or without spaces.
This is fixing the issue #7

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -54,7 +54,7 @@ git config user.email $ACTION_MAIL
 git pull https://${GH_PAT}@github.com/$OWNER/$REPO_NAME.wiki.git
 cd ..
 
-for i in $(find $MD_FOLDER -maxdepth 1 -type f -name '*.md' -execdir basename '{}' ';'); do
+for i in "$(find $MD_FOLDER -maxdepth 1 -type f -name '*.md' -execdir basename '{}' ';')"; do
```
Comment (GregoireW) [inline entrypoint.sh:57]: If MD_FOLDER have space you will end up with an error here.

Comment (mmornati) [reply entrypoint.sh:57]: I tested... adding the `"` it was the only way to let it work correctly. Which kind of error are you thinking about @GregoireW ?

Without the `"` around the command, the for will split even over spaces, creating problems due to missing files.

Comment (GregoireW) [reply entrypoint.sh:57]: my bad  shell protect the first level. it is ok disregard that.

**Review by GregoireW — APPROVED** [review]
LGTM
